IDS.Web.UI/Areas/Sales/Controllers/AccrualCustProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;

namespace IDS.Web.UI.Areas.Sales.Controllers
{
    public class AccrualCustProjectController  : IDS.Web.UI.Controllers.MenuController
    {
        public JsonResult GetData(string period)
        {
            if (string.IsNullOrEmpty(period))
                period = DateTime.Now.ToString("yyyyMM");
            else
            {
                DateTime datePeriod = Convert.ToDateTime(period);
                period = datePeriod.ToString("yyyyMM");
            }

            if (Session[IDS.Tool.GlobalVariable.SESSION_USER_ID] == null)
                throw new Exception("You do not have access to access this page");

            JsonResult result = new JsonResult();

            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecords = 0; // Total keseluruhan data
                int totalRecordsShowing = 0; // Total data setelah filter / search

                List<IDS.Sales.AccrualCustProject> accrualCustProj = IDS.Sales.AccrualCustProject.GetListAccrualCustProject(period);

                totalRecords = accrualCustProj.Count;

                //Sorting
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    switch (sortColumn.ToLower())
                    {
                        default:
                            accrualCustProj = accrualCustProj.OrderBy(sortColumn + " " + sortColumnDir).ToList();
                            break;
                    }
                }

                // Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    string searchValueLower = searchValue.ToLower();

                    accrualCustProj = accrualCustProj.Where(x => x.Period.ToString().Contains(searchValueLower) || 
                    x.Total.ToString().Contains(searchValueLower) || 
                    Tool.GeneralHelper.NullToString(x.Name, "").ToLower().Contains(searchValueLower)).ToList();
                }

                totalRecordsShowing = accrualCustProj.Count();

                // Paging
                accrualCustProj = accrualCustProj.Skip(skip).Take(pageSize).ToList();

                // Returning Json Data
                result = this.Json(new { draw = draw, recordsFiltered = totalRecordsShowing, recordsTotal = totalRecords, data = accrualCustProj }, JsonRequestBehavior.AllowGet);
            }
            catch
            {

            }

            return result;
        }

        public JsonResult GetDataDetail(string period)
        {
            //if (string.IsNullOrEmpty(period))
            //    period = DateTime.Now.ToString("yyyyMM");
            //else
            //{
            //    DateTime datePeriod = Convert.ToDateTime(period);
            //    period = datePeriod.ToString("yyyyMM");
            //}

            if (Session[IDS.Tool.GlobalVariable.SESSION_USER_ID] == null)
                throw new Exception("You do not have access to access this page");

            JsonResult result = new JsonResult();

            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecords = 0; // Total keseluruhan data
                int totalRecordsShowing = 0; // Total data setelah filter / search

                List<IDS.Sales.AccrualCustProject> accrualCustProjDet = IDS.Sales.AccrualCustProject.GetAccrualCustProjectDetail(period);

                totalRecords = accrualCustProjDet.Count;

                //Sorting
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    switch (sortColumn.ToLower())
                    {
                        default:
                            accrualCustProjDet = accrualCustProjDet.OrderBy(sortColumn + " " + sortColumnDir).ToList();
                            break;
                    }
                }

                // Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    string searchValueLower = searchValue.ToLower();

                    accrualCustProjDet = accrualCustProjDet.Where(x => x.Period.ToString().Contains(searchValueLower) ||
                    x.InvoiceNo.ToString().Contains(searchValueLower) ||
                    x.Amount.ToString().ToLower().Contains(searchValueLower)).ToList();
                }

                totalRecordsShowing = accrualCustProjDet.Count();

                // Paging
                accrualCustProjDet = accrualCustProjDet.Skip(skip).Take(pageSize).ToList();

                // Returning Json Data
                result = this.Json(new { draw = draw, recordsFiltered = totalRecordsShowing, recordsTotal = totalRecords, data = accrualCustProjDet }, JsonRequestBehavior.AllowGet);
            }
            catch
            {

            }

            return result;
        }

        // GET: Sales/AccrualCustProject
        public ActionResult Index()
        {
            if (Session[IDS.Tool.GlobalVariable.SESSION_USER_ID] == null)
                return RedirectToAction("index", "Main", new { area = "" });

            IDS.Web.UI.Models.GroupAccessLevel AccessLevel = IDS.Web.UI.Models.GroupAccessLevel.GetFormGroupAccess(Convert.ToString(Session[IDS.Tool.GlobalVariable.SESSION_USER_GROUP_CODE]), this.ControllerContext.RouteData.Values["controller"].ToString());

            if (AccessLevel.CreateAccess == -1 || AccessLevel.EditAccess == -1 || AccessLevel.DeleteAccess == -1)
            {
                RedirectToAction("Index", "Main", new { Area = "" });
            }

            ViewData["Page.Insert"] = AccessLevel.CreateAccess;
            ViewData["Page.Edit"] = AccessLevel.EditAccess;
            ViewData["Page.Delete"] = AccessLevel.DeleteAccess;

            ViewBag.UserMenu = MainMenu;
            ViewBag.UserLogin = Session[Tool.GlobalVariable.SESSION_USER_ID].ToString();

            return View();
        }

        [HttpGet]
        public ActionResult Edit(string invNo,string branch,string period)
        {
            if (Session[IDS.Tool.GlobalVariable.SESSION_USER_ID] == null)
                return RedirectToAction("index", "Main", new { area = "" });

            IDS.Web.UI.Models.GroupAccessLevel AccessLevel = IDS.Web.UI.Models.GroupAccessLevel.GetFormGroupAccess(Convert.ToString(Session[IDS.Tool.GlobalVariable.SESSION_USER_GROUP_CODE]), this.ControllerContext.RouteData.Values["controller"].ToString());

            if (AccessLevel.ReadAccess == -1 || AccessLevel.EditAccess == 0)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }

            ViewData["Page.Insert"] = AccessLevel.CreateAccess;
            ViewData["Page.Edit"] = AccessLevel.EditAccess;
            ViewData["Page.Delete"] = AccessLevel.DeleteAccess;

            if (string.IsNullOrEmpty(period))
                period = DateTime.Now.ToString("yyyyMM");
            else
            {
                DateTime datePeriod = Convert.ToDateTime(period);
                period = datePeriod.ToString("yyyyMM");
            }

            IDS.Sales.AccrualCustProject accrualCustProj = IDS.Sales.AccrualCustProject.GetAccrualCustProject(period,invNo,branch);

            if (Convert.ToBoolean(Session[IDS.Tool.GlobalVariable.SESSION_USER_BRANCH_HO_STATUS]))
            {
                ViewData["HOStatus"] = 1;
                ViewData["SelectListBranch"] = new SelectList(IDS.GeneralTable.Branch.GetBranchForDatasource(), "Value", "Text", branch);
            }
            else
            {
                ViewData["HOStatus"] = 0;
                ViewData["SelectListBranch"] = ViewData["SelectListBranch"] = new SelectList(IDS.GeneralTable.Branch.GetBranchForDatasource(Session[IDS.Tool.GlobalVariable.SESSION_USER_BRANCH_CODE].ToString()), "Value", "Text", Session[IDS.Tool.GlobalVariable.SESSION_USER_BRANCH_CODE].ToString());
            }

            ViewData["SelectListCurrency"] = new SelectList(IDS.GeneralTable.Currency.GetCurrencyForDataSource(), "Value", "Text", accrualCustProj.Ccy);

            ViewData["FormAction"] = 2;

            
            ViewData["PeriodDef"] = DateTime.ParseExact(period, "yyyyMM", null).ToString("MMM yyyy");

            ViewBag.UserMenu = MainMenu;
            ViewBag.UserLogin = Session[Tool.GlobalVariable.SESSION_USER_ID].ToString();

            return View("Create",accrualCustProj);

IDS.Web.UI/Areas/Sales/Views/AccrualCustProject/Create.cshtml
@model IDS.Sales.AccrualCustProject

<div class="modal fade" id="CreateEditForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle"></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "formCreateEdit" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.Hidden("FormAction", Convert.ToInt32(ViewData["FormAction"]))
                    @Html.Hidden("FormSave", "0");

                    <script type="text/javascript">
                        $('form#formCreateEdit').removeData("validator");
                        $('form#formCreateEdit').removeData("unobtrusiveValidation");
                        $.validator.unobtrusive.parse($('form#formCreateEdit'));
                    </script>

                    <div class="form-group row label">
                        @Html.LabelFor(model => model.InvoiceNo, htmlAttributes: new { @class = "col-form-label-sm col-sm-3" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.InvoiceNo, new { htmlAttributes = new { @class = "form-control form-control-sm bg-white", placeholder = "Invoice No" } })
                            @Html.ValidationMessageFor(model => model.InvoiceNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row label">
                        @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "col-form-label-sm col-sm-3" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.Period, new { htmlAttributes = new { @class = "form-control form-control-sm bg-white", placeholder = "Period" } })
                            @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row label">
                        @Html.LabelFor(model => model.Branch, htmlAttributes: new { @class = "col-form-label-sm col-sm-3" })
                        <div class="col-sm-9">
                            @Html.DropDownListFor(model => model.Branch, (SelectList)ViewData["SelectListBranch"], " ", new { @id = "cboBranch", @class = "form-control select2DDList", @style = "width:100%;" })
                            @Html.ValidationMessageFor(model => model.Branch, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row label">
                        @Html.LabelFor(model => model.Ccy, htmlAttributes: new { @class = "col-form-label-sm col-sm-3" })
                        <div class="col-sm-9">
                            @Html.DropDownListFor(model => model.Ccy, (SelectList)ViewData["SelectListCurrency"], " ", new { @id = "cboCcy", @class = "form-control select2DDList", @style = "width:100%;" })
                            @Html.ValidationMessageFor(model => model.Ccy, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row label">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "col-form-label-sm col-sm-3" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control form-control-sm bg-white", placeholder = "Amount" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row label">
                        @Html.LabelFor(model => model.GLStatus, htmlAttributes: new { @class = "col-form-label-sm col-sm-3 align-text-top", name = "GLStatus" })
                        <div class="col-md-9 align-text-bottom" style="vertical-align:text-bottom">
                            <input style="text-align:center; vertical-align:middle" type="checkbox" id="GLStatus" data-val="false" name="GLStatus" />
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" id="btnAddNew">Add New</button>*@
                <button type="button"  class="btn btn-primary" id="btnSave">Save</button>
                <button type="button" class="btn btn-default" id="btnClose" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Scripts/moment.min.js"></script>
}

<script type="text/javascript">
    $(document).ready(function () {
        $(".select2DDList").select2();

        $("#cboBranch").select2({
            dropdownParent: $("#CreateEditForm")
        });

        $("#cboCcy").select2({
            dropdownParent: $("#CreateEditForm")
        });

        flatpickr("#Period", {
            shorthand: true,
            dateFormat: "M-Y",
            altFormat: "F Y",
            defaultDate: ["today"],
            static: true,
            plugins: [new monthSelectPlugin({
                shorthand: true, //defaults to false
                dateFormat: "M Y", //defaults to "F Y"
                altFormat: "F Y"
            })],
        });

        $("#btnSave").click(function () {
            if (!$("form#formCreateEdit").valid()) {
                return false;
            }
            var confirmText = "";
            if ($("#FormAction").val() == 1) {
                confirmText = ("Are you sure want to save data ?");
            } else {
                //confirmText = ("Are you sure want to edit Currency Code : ?");
                confirmText = ("Are you sure want to edit Invoice No : " + $("#InvoiceNo").val() + " ?");
            }
            var answer = confirm(confirmText);

            if (answer) {
                if ($('#GLStatus').is(":checked")) {
                    $("#GLStatus").val(true);
                }

                if ($("#FormAction").val() == 1) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Create", "AccrualCustProject", new { Area = "Sales" })',
                        processData: false,
                        data: $("#formCreateEdit").serialize(),
                        success: function (respond) {
                            $("#FormSave").val("1");
                            alert(respond);
                        }
                    });
                }
                else {
                    $("#InvoiceNo").removeAttr('disabled');
                    $("#cboBranch").removeAttr('disabled');
                    $("#Period").removeAttr('disabled');
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Edit", "AccrualCustProject", new { Area = "Sales" })',
                        processData: false,
                        data: $("#formCreateEdit").serialize(),
                        success: function (respond) {
                            $("#FormSave").val("1");
                            alert(respond);
                        }
                    });

                    $("#Period").attr('disabled', 'disabled');
                    $("#InvoiceNo").attr('disabled', 'disabled');
                    $("#cboBranch").attr('disabled', 'disabled');
                }
            } else {
                return false;
            }

        }),

        $("#btnClose, .close").click(function () {
            $("#CreateEditForm").modal('hide');
            if ($("#FormSave").val() == "1") {
                window.location.href = '@Url.Action("index", "AccrualCustProject", new { Area = "Sales" })';
            }
        }),

        //$("#btnAddNew").click(function () {
        //    if (!$('#Period').val() == "") {
        //        var answer = confirm("Are you sure want to clear this form ?");

        //        if (answer) {
        //            $("form#formCreateEdit").trigger("reset");
        //            $(':input', '#formCreateEdit').not(':button, :submit, :reset, :hidden').val('');
        //            $("#Period").removeAttr('disabled');
        //            $("#InvoiceNo").removeAttr('disabled');
        //            $("#cboBranch").removeAttr('disabled');
        //            $("#cboCcy").removeAttr('disabled');
        //            $("#GLStatus").removeAttr('disabled');
        //            $("#FormAction").val("1");
        //            $("#FormSave").val("1");
        //        }
        //        else {
        //            e.preventDefault();
        //        }
        //    }
        //    else {
        //        e.preventDefault();
        //    }
        //})

        $('#Amount').keypress(function (event) {
            return isNumber(event, this)
        });

        function isNumber(evt, element) {
            var charCode = (evt.which) ? evt.which : event.keyCode
            if (
                (charCode != 46 || $(element).val().indexOf('.') != -1) &&      // “.” CHECK DOT, AND ONLY ONE.
                (charCode < 48 || charCode > 57))
                return false;
            return true;
        }
    });

</script>