IDS.Web.UI/Areas/FixedAsset/Controllers/FATransController.cs
using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;

namespace IDS.Web.UI.Areas.FixedAsset.Controllers
{
    public class FATransController : IDS.Web.UI.Controllers.MenuController
    {
        public JsonResult GetData(string branch)
        {
            if (Session[IDS.Tool.GlobalVariable.SESSION_USER_ID] == null)
                throw new Exception("You do not have access to access this page");

            JsonResult result = new JsonResult();

            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                //int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int pageSize = 0;
                switch (length)
                {
                    case null:
                        break;
                    case "-1":
                        pageSize = 0;
                        break;
                    default:
                        pageSize = Convert.ToInt32(length);
                        break;
                }

                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecords = 0; // Total keseluruhan data
                int totalRecordsShowing = 0; // Total data setelah filter / search

                List<IDS.FixedAsset.FATrans> trans = IDS.FixedAsset.FATrans.GetFATrans(branch);

                totalRecords = trans.Count;

                // Sorting    
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    trans = trans.OrderBy(sortColumn + " " + sortColumnDir).ToList();
                }

                // Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    string lowerSearchValue = searchValue.ToLower();

                    trans = trans.Where(x => Tool.GeneralHelper.NullToString(x.TransNo).ToLower().Contains(lowerSearchValue) ||
                                            Tool.GeneralHelper.NullToString(x.TransCode).ToLower().Contains(lowerSearchValue) ||
                                            Tool.GeneralHelper.NullToString(x.AssetNo).ToLower().Contains(lowerSearchValue) ||
                                            Tool.GeneralHelper.NullToString(x.Currency).ToLower().Contains(lowerSearchValue) ||
                                            Tool.GeneralHelper.NullToDateTime(x.TransDate, DateTime.Now.Date).ToString(Tool.GlobalVariable.DEFAULT_DATE_FORMAT).ToLower().Contains(lowerSearchValue) ||
                                            Tool.GeneralHelper.NullToString(x.Department).ToLower().Contains(lowerSearchValue) ||
                                            x.OperatorID.ToLower().Contains(lowerSearchValue) ||
                                            x.LastUpdate.ToString(Tool.GlobalVariable.DEFAULT_DATETIME_FORMAT).ToLower().Contains(lowerSearchValue)).ToList();
                }

                totalRecordsShowing = trans.Count();

                // Paging
                if (pageSize > 0)
                    trans = trans.Skip(skip).Take(pageSize).ToList();

                // Returning Json Data
                result = this.Json(new { draw = draw, recordsFiltered = totalRecordsShowing, recordsTotal = totalRecords, data = trans }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
            }

            return result;
        }

        // GET: FixedAsset/FATrans
        public ActionResult Index()
        {
            if (Session[IDS.Tool.GlobalVariable.SESSION_USER_ID] == null)
                return RedirectToAction("index", "Main", new { area = "" });

            IDS.Web.UI.Models.GroupAccessLevel AccessLevel = IDS.Web.UI.Models.GroupAccessLevel.GetFormGroupAccess(Convert.ToString(Session[IDS.Tool.GlobalVariable.SESSION_USER_GROUP_CODE]), this.ControllerContext.RouteData.Values["controller"].ToString());

            if (AccessLevel.CreateAccess == -1 || AccessLevel.EditAccess == -1 || AccessLevel.DeleteAccess == -1)
            {
                RedirectToAction("Index", "Main", new { Area = "" });
            }

            ViewData["Page.Insert"] = AccessLevel.CreateAccess;
            ViewData["Page.Edit"] = AccessLevel.EditAccess;
            ViewData["Page.Delete"] = AccessLevel.DeleteAccess;

            ViewBag.UserMenu = MainMenu;
            ViewBag.UserLogin = Session[Tool.GlobalVariable.SESSION_USER_ID].ToString();

            ViewData["HO"] = 0;

            if (Convert.ToBoolean(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_HO_STATUS]) == true)
            {
                ViewData["HO"] = 1;
            }

            if (Session[Tool.GlobalVariable.SESSION_USER_BRANCH_HO_STATUS] != null && Convert.ToBoolean(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_HO_STATUS]) == true)
            {
                ViewData["BranchList"] = new SelectList(IDS.GeneralTable.Branch.GetBranchForDatasource(), "Value", "Text", Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE]));
            }
            else
            {
                ViewData["BranchList"] = new SelectList(IDS.GeneralTable.Branch.GetBranchForDatasource(Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE])), "Value", "Text", Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE]));
            }

            return View();
        }

        // GET: FixedAsset/FATrans/Create
        public ActionResult Create()
        {
            if (Session[IDS.Tool.GlobalVariable.SESSION_USER_ID] == null)
                return RedirectToAction("index", "Main", new { area = "" });

            IDS.Web.UI.Models.GroupAccessLevel AccessLevel = IDS.Web.UI.Models.GroupAccessLevel.GetFormGroupAccess(Convert.ToString(Session[IDS.Tool.GlobalVariable.SESSION_USER_GROUP_CODE]), this.ControllerContext.RouteData.Values["controller"].ToString());

            if (AccessLevel.ReadAccess == -1 || AccessLevel.CreateAccess == 0)
            {
                //return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
                return RedirectToAction("error403", "error", new { area = "" });
            }

            ViewBag.UserMenu = MainMenu;
            ViewBag.UserLogin = Session[Tool.GlobalVariable.SESSION_USER_ID].ToString();

            if (Convert.ToBoolean(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_HO_STATUS]) == true)
            {
                ViewData["HO"] = 1;
            }

            List<SelectListItem> branches = IDS.GeneralTable.Branch.GetBranchForDatasource();

            if (Session[Tool.GlobalVariable.SESSION_USER_BRANCH_HO_STATUS] != null && Convert.ToBoolean(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_HO_STATUS]) == true)
            {
                ViewData["BranchList"] = new SelectList(branches, "Value", "Text", Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE]));
            }
            else
            {
                ViewData["BranchList"] = new SelectList(IDS.GeneralTable.Branch.GetBranchForDatasource(Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE])), "Value", "Text", Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE]));
            }

            ViewData["BranchListAll"] = new SelectList(branches, "Value", "Text");
            ViewData["FATransCodeList"] = new SelectList(IDS.FixedAsset.FATrans.GetFATransCodeList(), "Value", "Text");
            ViewData["AssetList"] = new SelectList(IDS.FixedAsset.FAAsset.getFAAssetNoForDatasource(Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE])), "Value", "Text", null);
            ViewData["CCyList"] = new SelectList(IDS.GeneralTable.Currency.GetCurrencyForDataSource(), "Value", "Text", IDS.GeneralTable.Syspar.GetInstance().BaseCCy);
            ViewData["COAList"] = new SelectList(IDS.GLTable.ChartOfAccount.GetCOAExProtAccForDatasource(IDS.GeneralTable.Syspar.GetInstance().BaseCCy), "Value", "Text", IDS.GeneralTable.Syspar.GetInstance().BaseCCy);
            ViewData["ToBranchList"] = new SelectList(IDS.GeneralTable.Branch.GetBranchForDatasource(Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE])), "Value", "Text", null);
            ViewData["DeptList"] = new SelectList(IDS.GeneralTable.Department.GetDepartmentForDataSource(Tool.GeneralHelper.NullToString(Session[Tool.GlobalVariable.SESSION_USER_BRANCH_CODE])), "Value", "Text", null);
            ViewData["LocationList"] = new SelectList(IDS.GeneralTable.Location.GetLocationDatasource(), "Value", "Text");

            ViewData["Page.Insert"] = AccessLevel.CreateAccess;
            ViewData["Page.Edit"] = AccessLevel.EditAccess;
            ViewData["Page.Delete"] = AccessLevel.DeleteAccess;

            ViewData["FormAction"] = 1;

            return View("Create", new IDS.FixedAsset.FATrans() { TransNo = "< A U T O >", BaseTotalPrice = 0, BookValue = IDS.FixedAsset.FASchedule.GetBookValue(DateTime.Now.ToString("yyyyMM"),""), Currency = IDS.GeneralTable.Syspar.GetInstance().BaseCCy, UnitPrice = 0, TotalPrice = 0 });
        }

        // POST: FixedAsset/FATrans/Create
        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateAntiForgeryToken]

IDS.Web.UI/Areas/FixedAsset/Views/FATrans/Index.cshtml
@model IEnumerable<IDS.FixedAsset.FATrans>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Asset Transaction List";
}

@section Styles {
    <link rel="stylesheet" href="~/Content/DataTables/datatables.css" />
    <link rel="stylesheet" href="~/Content/DataTables/DataTables-1.10.25/css/dataTables.bootstrap5.min.css">
    @*<link rel="stylesheet" href="~/Content/DataTables/Select-1.3.3/css/select.bootstrap5.min.css" />*@
    <link href="~/Content/Select2/css/select2.min.css" rel="stylesheet" type="text/css" />
    @*<link rel="stylesheet" href="~/Content/DataTables/DataTables-1.10.25/css/jquery.dataTables.css">*@
    <link href="~/Content/Select2/css/select2.min.css" rel="stylesheet" type="text/css" />
}


<div class="row">
    <div class="col-sm-6 col-md-6 col-6">
        <h4>@ViewBag.Title</h4>
    </div>
    <div class="col-sm-6 col-md-6 col-6">
        <div class="text-right">
            <p>
                @{
                    if (Convert.ToInt32(ViewData["Page.Insert"]) == 1)
                    {
                        <a href='@Url.Action("Create", "FATrans", new { Area = "FixedAsset" })' title="Input Fixed Asset Transaction" class="btn btn-sm btn-primary">
                            <i class="fas fa-plus"></i>
                        </a>
                    }
                    else
                    {
                        <a href="#" class="btn btn-sm btn-primary" title="Input Fixed Asset Transaction" onclick="NoAccess()">
                            <i class="fas fa-plus"></i>
                        </a>
                    }

                    if (Convert.ToInt32(ViewData["Page.Edit"]) == 1)
                    {
                        <a class="btn btn-sm btn-info" title="Edit Fixed Asset Transaction" onclick="LoadEditForm()">
                            <i class="fas fa-edit"></i>
                        </a>
                    }
                    else
                    {
                        <a class="btn btn-sm btn-info" onclick="NoAccess()" title="Edit Fixed Asset Transaction" disabled="disabled">
                            <i class="fas fa-edit"></i>
                        </a>
                    }

                    if (Convert.ToInt32(ViewData["Page.Delete"]) == 1)
                    {
                        <a onclick="Delete()" class="btn btn-sm btn-danger" title="Delete Fixed Asset Transaction" href="#">
                            <i class="fas fa-trash"></i>
                        </a>
                    }
                    else
                    {
                        <a onclick="NoAccess()" class="btn btn-sm btn-danger" title="Delete Fixed Asset Transaction" href="#">
                            <i class="fas fa-trash"></i>
                        </a>
                    }
                }
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="form-group row">
            @Html.Label("Branch :", htmlAttributes: new { @class = "col-form-label-sm col-sm-2" })
            <div class="col-sm-10">
                @Html.DropDownList("cboBranch", (ViewData["BranchList"] as SelectList), new { @class = "form-control form-control-sm select2DDList", @style = "width: 100%;" })
            </div>
        </div>

    </div>
    <div class="col-sm-6">
        &nbsp;
    </div>
</div>


@Html.Hidden("HO", Convert.ToInt32(ViewData["HO"]))

<div class="table-responsive table-responsive-sm p-2 bg-white border">
    <table id="tableData" class="table table-bordered table-hover w-100">
        <thead>
            <tr>
                <th class="align-middle"></th>
                <th class="align-middle">Trans No</th>
                <th class="align-middle">Code</th>
                <th class="align-middle">Asset No</th>
                <th class="align-middle">Ccy</th>
                <th class="align-middle">Trans. Date</th>
                <th class="align-middle">Dept.</th>
                <th class="align-middle">Operator</th>
                <th class="align-middle">Last Update</th>
                <th class="align-middle">Status</th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts {
    <script type="text/javascript" src="~/Scripts/moment.min.js"></script>
    <script type="text/javascript" src="~/Content/DataTables/datatables.min.js"></script>
    <script type="text/javascript" src="~/Content/DataTables/DataTables-1.10.25/js/dataTables.bootstrap5.min.js"></script>
    <script type="text/javascript" src="~/Content/Select2/js/select2.full.min.js"></script>

    <script type="text/javascript">
        var HOSStatus = $("#HO").val();
        var cBranch = $("#cboBranch").val();

        $(document).ready(function () {
            if (HOSStatus == 0) {
                $("#cboBranch").prop('disabled', 'true');
            }
            LoadData(cBranch);
        });



        function LoadData(selBranch) {
            $('#tableData').DataTable
            ({
                "destroy": true,
                "columnDefs": [
                    {
                        "targets": 'no-sort',
                        "orderable": false,
                    },
                    {
                        "data": null,
                        "width": "20px",
                        "defaultContent": '',
                        "orderable": false,
                        "className": "select-checkbox",
                        "checkboxes": {
                            "selectRow": true
                        },
                        "targets": [0]
                    },
                    {
                        "orderable": true,
                        "targets": [1]
                    },
                    {
                        "width": "30px",
                        "orderable": true,
                        "targets": [2]
                    },
                    {
                        "width": "100px",
                        "orderable": true,
                        "targets": [3]
                    },
                    {
                        "width": "40",
                        "orderable": true,
                        "targets": [4]
                    },
                    {
                        "width": "70px",
                        "orderable": true,
                        "targets": [5]
                    },
                    {
                        "width": "50px",
                        "orderable": true,
                        "targets": [6]
                    },
                    {
                        "width": "80px",
                        "orderable": true,
                        "targets": [7]
                    },
                    {
                        "width": "110px",
                        "orderable": true,
                        "targets": [8]
                    },
                    {
                        "width": "10px",
                        "orderable": true,
                        "className": "text-center",
                        "targets": [9]
                    },
                ],
                "select": {
                    "style": 'os'
                },
                "language":
                {
                    "search": "",
                    "searchPlaceholder": "Search...",
                    "emptyTable": "No record found.",
                    "processing": "<div class='overlay custom-loader-background'><i class='fa fa-cog fa-spin custom-loader-color'></i></div>"
                },
                "processing": "true",
                "order": [[1, "asc"]],
                "serverSide": "true",
                "lengthMenu": [[1, 10, 20, 50, 100, 1000, -1], [1, 10, 20, 50, 100, 1000, "All"]],
                "pageLength": 10,
                "ajax":
                {
                    "url": '@Url.Action("GetData", "FATrans", new { Area = "FixedAsset" })',
                    "type": "POST",
                    "dataType": "JSON",
                    "data": { "branch": selBranch },
                },
                "columns": [
                    { "data": null },
                    { "data": "TransNo", "name": "TransNo" },
                    { "data": "TransCode", "name": "TransCode" },
                    { "data": "AssetNo", "name": "AssetNo" },
                    { "data": "Currency", "name": "Currency" },
                    {
                        "data": "TransDate", "name": "TransDate",
                        "render": function (data, type, row, meta) {
                            return moment(row.TransDate).format('DD/MMM/YYYY');
                        }
                    },
                    { "data": "Department", "name": "Department" },
                    { "data": "OperatorID", "name": "OperatorID" },
                    {
                        "data": "LastUpdate", "name": "LastUpdate",
                        "render": function (data, type, row, meta) {
                            return moment(row.LastUpdate).format('DD/MMM/YYYY HH:mm:ss');
                        }
                    },
                    {
                        "data": "Status", "name": "Status",
                        "render": function (data, type, row, meta) {
                            switch (data) {
                                case 0:
                                    return '';
                                    break;
                                case 1:
                                    return '<img src="../Images/icon/status-processed-16.png" alt="Processed" title="Processed">';
                                    break;
                                case 2:
                                    return '<img src="../Images/icon/status-cancel-16.png" alt="Processed" title="Cancelled">';
                                    break;
                                default:
                                    return '';
                                    break;
                            }
                        }
                    },
                ]
            });
        }


        $('#cboBranch').change(function () {
            var value = $(this).val();
            LoadData(value);
        });

        function LoadCreateNewForm() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("Create", "FATrans", new { Area = "FixedAsset" })',
                contentType: 'application/html; charset=utf-8',
                dataType: 'html',
                success: function (result) {
                    $('#PartialSection').empty();
                    $("#PartialSection").html(result);
                },
                error: function (status) {
                    alert('');
                }
            });
        }

        function LoadEditForm() {

            var form = this;
            var selRow = $("#tableData").DataTable().rows('.selected').data();
            var assetNo = null;
            var branchCode = null;


            if (selRow.length > 0) {
                transNo = selRow[0]["TransNo"];
                branchCode = $('#cboBranch').val();

                var _url = '@Url.Action("Edit", "FATrans", new { Area = "FixedAsset" })?transNo=XXX&branchCode=ZZZ';
                _url = _url.replace("XXX", transNo);
                _url = _url.replace("ZZZ", branchCode);
                document.location = _url;

                $('#TransNo').attr('readonly')
            }
            else {
                alert("Please select data to be edit");
            }
        }

        function Delete() {
            var form = this;
            var selRow = $("#tableData").DataTable().rows('.selected').data();

            if (selRow == null || selRow == 'undefined' || selRow.length == 0) {
                alert("Please select the data you want to delete");
                return false;
            }

            var dataCollection = '';
            var data = '';

            $.each(selRow, function (index, row) {
                data += row["TransNo"] + ';' + $('#cboBranch').val() + ',';
                dataCollection += '[' + row["TransNo"] + '] - ' + row["AssetNo"] + "\n";
            })

            var answer = confirm("You are about to delete data:\n" + dataCollection + "\nAre you sure want to delete the data ?");

            if (answer) {
                if (dataCollection.length > 0) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "FATrans", new { Area = "FixedAsset" })',
                        data: { "transList": data },
                        dataType: 'JSON',
                        success: function (respond) {
                            switch (respond) {
                                case "NoAccess":
                                    window.location.href = '@Server.MapPath("~/Views/Shared/View403.cshtml")'
                                    break;
                                case "Success":
                                    alert(respond);
                                    window.location.href = '@Url.Action("index", "FATrans", new { Area = "FixedAsset" })'
                                    break;
                                default:
                                    alert(respond);
                                    window.location.href = '@Url.Action("index", "FATrans", new { Area = "FixedAsset" })'
                                    break;
                            }

                        },
                        error: function (respond) {
                            alert(respond);
                        }
                    })
                }
            }
            else {
                return false;
            }
        }
    </script>
}